// Copyright 2021 clouWay eood.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: clouway/rpc/fileserve/fileserve.proto

package fileserve

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Binary is representing a Binary message that to the send to the backend
// once the data is available.
type BinaryFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The content-type to be provided.
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// The name of the file.
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// The binary content.
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BinaryFile) Reset() {
	*x = BinaryFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clouway_rpc_fileserve_fileserve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryFile) ProtoMessage() {}

func (x *BinaryFile) ProtoReflect() protoreflect.Message {
	mi := &file_clouway_rpc_fileserve_fileserve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryFile.ProtoReflect.Descriptor instead.
func (*BinaryFile) Descriptor() ([]byte, []int) {
	return file_clouway_rpc_fileserve_fileserve_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BinaryFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *BinaryFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_clouway_rpc_fileserve_fileserve_proto protoreflect.FileDescriptor

var file_clouway_rpc_fileserve_fileserve_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6c, 0x6f, 0x75, 0x77, 0x61, 0x79, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42,
	0x89, 0x01, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x77, 0x61, 0x79, 0x2e,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x77, 0x61, 0x79,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x42, 0x11, 0x52, 0x70, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x77, 0x61, 0x79, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_clouway_rpc_fileserve_fileserve_proto_rawDescOnce sync.Once
	file_clouway_rpc_fileserve_fileserve_proto_rawDescData = file_clouway_rpc_fileserve_fileserve_proto_rawDesc
)

func file_clouway_rpc_fileserve_fileserve_proto_rawDescGZIP() []byte {
	file_clouway_rpc_fileserve_fileserve_proto_rawDescOnce.Do(func() {
		file_clouway_rpc_fileserve_fileserve_proto_rawDescData = protoimpl.X.CompressGZIP(file_clouway_rpc_fileserve_fileserve_proto_rawDescData)
	})
	return file_clouway_rpc_fileserve_fileserve_proto_rawDescData
}

var file_clouway_rpc_fileserve_fileserve_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clouway_rpc_fileserve_fileserve_proto_goTypes = []interface{}{
	(*BinaryFile)(nil), // 0: BinaryFile
}
var file_clouway_rpc_fileserve_fileserve_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clouway_rpc_fileserve_fileserve_proto_init() }
func file_clouway_rpc_fileserve_fileserve_proto_init() {
	if File_clouway_rpc_fileserve_fileserve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clouway_rpc_fileserve_fileserve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clouway_rpc_fileserve_fileserve_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clouway_rpc_fileserve_fileserve_proto_goTypes,
		DependencyIndexes: file_clouway_rpc_fileserve_fileserve_proto_depIdxs,
		MessageInfos:      file_clouway_rpc_fileserve_fileserve_proto_msgTypes,
	}.Build()
	File_clouway_rpc_fileserve_fileserve_proto = out.File
	file_clouway_rpc_fileserve_fileserve_proto_rawDesc = nil
	file_clouway_rpc_fileserve_fileserve_proto_goTypes = nil
	file_clouway_rpc_fileserve_fileserve_proto_depIdxs = nil
}
